version: 2.1
orbs:
    ruby: circleci/ruby@1
jobs:
  build:
    docker:
      - image: recursecenter/community-ci:ruby-2.6.10
      - image: cimg/postgres:14.0-postgis
        environment:
          POSTGRES_DB: community_test
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
      - image: redis:4.0
      - image: elasticsearch:2.4.6
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: root
      PGPASSWORD: password
      RAILS_ENV: test
      PAGER: cat
      REDIS_URL: redis://localhost:6379
      JASMINE_CONFIG_PATH=test/javascripts/support/jasmine.yml
    steps:
      - checkout

      - ruby/install-deps:
          key: gems-{{ .Environment.CACHE_VERSION }}
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bin/rails db:structure:load --trace'
          name: Database setup

      - run:
          name: Build Elasticsearch index
          command: bin/rails search:rebuild

      - restore_cache:
          keys:
            - community-frontend-deps-{{ .Environment.CACHE_VERSION }}-{{ checksum "client/project.clj" }}
            - community-frontend-deps-{{ .Environment.CACHE_VERSION }}-

      - run:
          name: Build front-end tests
          command: cd client && lein cljsbuild once test

      - save_cache:
          key: community-frontend-deps-{{ .Environment.CACHE_VERSION }}-{{ checksum "client/project.clj" }}
          paths:
            - ~/.lein
            - ~/.m2

      - restore_cache:
          keys:
            - community-assets-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
            - community-assets-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - community-assets-{{ .Environment.CACHE_VERSION }}-

      - run:
          name: Tests
          command: bin/rails test && bin/rails jasmine:ci

      - save_cache:
          key: community-assets-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - tmp/cache

      # Save artifacts
      - store_test_results:
          path: test/reports
